# netlify.toml

# Build settings for your React app
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# --- Rule 1: API Proxy (must come first) ---
# This forwards requests from /api/* to your serverless functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# --- Rule 2: Single-Page App (SPA) Catch-all (must come last) ---
# This makes sure that direct visits to routes like /status work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
#---CSP  
[[headers]]
  # Apply headers to all paths
  for = "/*"
  [headers.values]
    # --- Content Security Policy ---
    # Combine user directives + fix for worker-src
    Content-Security-Policy = """
      default-src 'self'; \
      script-src 'self' https://eu-test.oppwa.com 'nonce-${NONCE_ID}'; \
      style-src 'self' https://eu-test.oppwa.com 'unsafe-inline'; \
      frame-src 'self' https://eu-test.oppwa.com; \
      connect-src 'self' https://eu-test.oppwa.com *.netlify.app; \
      img-src 'self' https://eu-test.oppwa.com data:; \
      worker-src 'self' blob:; \
    """
